import { huskyIdentifier } from './hookScript'

export function isHusky(data: string): boolean {
  return data.indexOf(huskyIdentifier) !== -1
}

export function isGhooks(data: string): boolean {
  return data.indexOf('// Generated by ghooks. Do not edit this file.') !== -1
}

export function isPreCommit(data: string): boolean {
  return data.indexOf('./node_modules/pre-commit/hook') !== -1
}
